export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const POST_ERROR = 'POST_ERROR'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SELECT_TOTAL = 'SELECT_TOTAL'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ITEM_LENGTH = 'ITEM_LENGTH'
export const ORDER = 'ORDER'
export const GET_LOCATION = 'GET_LOCATION'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_PRODUCT_FILTER = 'GET_PRODUCT_FILTER'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const REMOVE_ALL_ITEMS = 'REMOVE_ALL_ITEMS'
export const SET_HISTORY = 'SET_HISTORY'
export const SAVE_FOR_LATER = 'SAVE_FOR_LATER'
export const GET_CATEGORY_TREND = 'GET_CATEGORY_TREND'
export const GET_CATEGORY_TREND2 = 'GET_CATEGORY_TREND2'
export const GET_CATEGORY_TREND3 = 'GET_CATEGORY_TREND3'
export const GET_CATEGORY_TREND4 = 'GET_CATEGORY_TREND4'
export const GET_CATEGORY_TREND5 = 'GET_CATEGORY_TREND5'
export const GET_CATEGORY_TREND6 = 'GET_CATEGORY_TREND6'
export const GET_CATEGORY_TREND7 = 'GET_CATEGORY_TREND7'
export const SET_HISTORY_RELATED = 'SET_HISTORY_RELATED'
export const FILTER_PROPERTIES = 'FILTER_PROPERTIES'
export const GET_REVIEWS = 'GET_REVIEWS'
export const REVIEW = 'REVIEW'






